services:
  backend:
    hostname: cp.xandr
    domainname: cp.xandr.pp.ua
    build:
     context: ./
     dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
     - 80:80
     - 443:443 
     - 8083:8083